/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package physics.Package;

import java.io.File;
import java.io.FileInputStream;
import java.io.InputStream;
import javax.swing.JOptionPane;
import sun.audio.AudioPlayer;
import sun.audio.AudioStream;

/**
 *
 * @author Mahit
 */
public class physicsLearning extends javax.swing.JFrame {
AudioStream music;
    /**
     * Creates new form physicsLearning
     */
    public physicsLearning() {
        initComponents();
      

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlK = new javax.swing.JPanel();
        btnK = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        pnlForces = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        btnForces = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        pnlEnergy = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        btnEnergy = new javax.swing.JButton();
        pnlWaves = new javax.swing.JPanel();
        btnWaves = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        pnlE = new javax.swing.JPanel();
        btnE = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        pnlK.setBackground(new java.awt.Color(0, 204, 102));
        pnlK.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        pnlK.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnK.setBackground(new java.awt.Color(204, 0, 0));
        btnK.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        btnK.setForeground(new java.awt.Color(0, 0, 0));
        btnK.setText("Kinematics");
        btnK.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnKActionPerformed(evt);
            }
        });
        pnlK.add(btnK, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 220, -1, -1));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/physicsApplication/resources/ISU pic 2.png"))); // NOI18N
        pnlK.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 30, 220, 150));

        getContentPane().add(pnlK, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 70, 270, 270));

        pnlForces.setBackground(new java.awt.Color(0, 0, 255));
        pnlForces.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        pnlForces.setMaximumSize(new java.awt.Dimension(240, 215));
        pnlForces.setMinimumSize(new java.awt.Dimension(240, 215));
        pnlForces.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/physicsApplication/resources/newtons-laws-678x381.jpg"))); // NOI18N
        pnlForces.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 50, -1, -1));

        btnForces.setBackground(new java.awt.Color(204, 0, 0));
        btnForces.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        btnForces.setText("Forces");
        btnForces.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnForcesActionPerformed(evt);
            }
        });
        pnlForces.add(btnForces, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 220, -1, -1));

        getContentPane().add(pnlForces, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 70, 270, 270));

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Please Begin by Selecting a Topic to learn about Today");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 10, -1, -1));

        pnlEnergy.setBackground(new java.awt.Color(255, 255, 51));
        pnlEnergy.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        pnlEnergy.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/physicsApplication/resources/energy-week-900x600-min.jpg"))); // NOI18N
        pnlEnergy.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 20, -1, -1));

        btnEnergy.setBackground(new java.awt.Color(204, 204, 204));
        btnEnergy.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        btnEnergy.setForeground(new java.awt.Color(0, 0, 0));
        btnEnergy.setText("Energy");
        btnEnergy.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEnergyActionPerformed(evt);
            }
        });
        pnlEnergy.add(btnEnergy, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 220, -1, -1));

        getContentPane().add(pnlEnergy, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 350, 270, 270));

        pnlWaves.setBackground(new java.awt.Color(0, 51, 51));
        pnlWaves.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        pnlWaves.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnWaves.setBackground(new java.awt.Color(255, 255, 102));
        btnWaves.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        btnWaves.setForeground(new java.awt.Color(0, 0, 0));
        btnWaves.setText("Waves and Sound");
        btnWaves.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnWavesActionPerformed(evt);
            }
        });
        pnlWaves.add(btnWaves, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 230, -1, -1));

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/physicsApplication/resources/4354437_orig.jpg"))); // NOI18N
        pnlWaves.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 20, -1, -1));

        getContentPane().add(pnlWaves, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 350, 270, 270));

        pnlE.setBackground(new java.awt.Color(204, 0, 204));
        pnlE.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        pnlE.setMaximumSize(new java.awt.Dimension(240, 215));
        pnlE.setMinimumSize(new java.awt.Dimension(240, 215));
        pnlE.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnE.setBackground(new java.awt.Color(255, 102, 102));
        btnE.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        btnE.setForeground(new java.awt.Color(0, 0, 0));
        btnE.setText("Electricity and Magnetism");
        btnE.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEActionPerformed(evt);
            }
        });
        pnlE.add(btnE, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 230, -1, -1));

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/physicsApplication/resources/Relationship between electricity and magnetism.png"))); // NOI18N
        pnlE.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 10, -1, -1));

        getContentPane().add(pnlE, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 70, 260, 270));

        jLabel4.setBackground(new java.awt.Color(255, 0, 0));
        jLabel4.setForeground(new java.awt.Color(204, 255, 255));
        jLabel4.setOpaque(true);
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 890, 910));

        setBounds(0, 0, 901, 700);
    }// </editor-fold>//GEN-END:initComponents

    private void btnKActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnKActionPerformed
        // TODO add your handling code here:
        new kinematicsQuestion1().setVisible(true);
        this.setVisible(false);
        
        try {
            if (evt.getSource() == btnK) {
                AudioPlayer.player.stop();
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e);
        }
    

    
    }//GEN-LAST:event_btnKActionPerformed

    private void btnEActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEActionPerformed
        // TODO add your handling code here:
        new electricityQuestion1().setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_btnEActionPerformed

    private void btnWavesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnWavesActionPerformed
        // TODO add your handling code here:\
        new wavesQuestionOne().setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_btnWavesActionPerformed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        // TODO add your handling code here:

        try {
           InputStream music = new FileInputStream(new File("src\\Audio\\Jeopardy-theme-song.wav"));
            AudioStream audios = new AudioStream(music);
            AudioPlayer.player.start(audios);
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e.getLocalizedMessage());
        }

    }//GEN-LAST:event_formWindowOpened

    private void btnForcesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnForcesActionPerformed
        // TODO add your handling code here:
        new forcesQuestion1().setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_btnForcesActionPerformed

    private void btnEnergyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEnergyActionPerformed
        // TODO add your handling code here:
        new energyQuestionOne().setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_btnEnergyActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                

}
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(physicsLearning.class
.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        

} catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(physicsLearning.class
.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        

} catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(physicsLearning.class
.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        

} catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(physicsLearning.class
.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new physicsLearning().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnE;
    private javax.swing.JButton btnEnergy;
    private javax.swing.JButton btnForces;
    private javax.swing.JButton btnK;
    private javax.swing.JButton btnWaves;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel pnlE;
    private javax.swing.JPanel pnlEnergy;
    private javax.swing.JPanel pnlForces;
    private javax.swing.JPanel pnlK;
    private javax.swing.JPanel pnlWaves;
    // End of variables declaration//GEN-END:variables
}
